return {
  "meanderingprogrammer/render-markdown.nvim",
  dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-mini/mini.nvim" }, -- if you use the mini.nvim suite
  -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-mini/mini.icons' },        -- if you use standalone mini plugins
  -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons

  ---@module 'render-markdown'
  opts = {
    heading = {
      enabled = true,
      atx = true,
      setext = true,
      sign = true,
      icons = { "󰎥  ", "󰎨  ", "󰎫  ", "󰎲  ", "󰎯  ", "󰎴  " },
      position = "inline",
      signs = { "󰫎 " },
      width = "full",
      border = false,
      border_virtual = true,
      border_prefix = true,
      above = "▄",
      below = "▀",
      backgrounds = {
        "RenderMarkdownH1Bg",
        "RenderMarkdownH2Bg",
        "RenderMarkdownH3Bg",
        "RenderMarkdownH4Bg",
        "RenderMarkdownH5Bg",
        "RenderMarkdownH6Bg",
      },
      foregrounds = {
        "RenderMarkdownH1",
        "RenderMarkdownH2",
        "RenderMarkdownH3",
        "RenderMarkdownH4",
        "RenderMarkdownH5",
        "RenderMarkdownH6",
      },
      custom = {},
    },
    latex = {
      enabled = true,
      inline = true,
      block = true,
      converter = "latex2text",
    },
    render_modes = true,
    callout = {
      note = {
        raw = "[!note]",
        rendered = "󰋽 note",
        highlight = "rendermarkdowninfo",
        category = "github",
      },
      tip = {
        raw = "[!tip]",
        rendered = "󰌶 tip",
        highlight = "rendermarkdownsuccess",
        category = "github",
      },
      important = {
        raw = "[!important]",
        rendered = "󰅾 important",
        highlight = "rendermarkdownhint",
        category = "github",
      },
      warning = {
        raw = "[!warning]",
        rendered = "󰀪 warning",
        highlight = "rendermarkdownwarn",
        category = "github",
      },
      caution = {
        raw = "[!caution]",
        rendered = "󰳦 caution",
        highlight = "rendermarkdownerror",
        category = "github",
      },
      abstract = {
        raw = "[!abstract]",
        rendered = "󰨸 abstract",
        highlight = "rendermarkdowninfo",
        category = "obsidian",
      },
      summary = {
        raw = "[!summary]",
        rendered = "󰨸 summary",
        highlight = "rendermarkdowninfo",
        category = "obsidian",
      },
      tldr = {
        raw = "[!tldr]",
        rendered = "󰨸 tldr",
        highlight = "rendermarkdowninfo",
        category = "obsidian",
      },
      info = {
        raw = "[!info]",
        rendered = "󰋽 info",
        highlight = "rendermarkdowninfo",
        category = "obsidian",
      },
      todo = {
        raw = "[!todo]",
        rendered = "󰗡 todo",
        highlight = "rendermarkdowninfo",
        category = "obsidian",
      },
      hint = {
        raw = "[!hint]",
        rendered = "󰌶 hint",
        highlight = "rendermarkdownsuccess",
        category = "obsidian",
      },
      success = {
        raw = "[!success]",
        rendered = "󰄬 success",
        highlight = "rendermarkdownsuccess",
        category = "obsidian",
      },
      check = {
        raw = "[!check]",
        rendered = "󰄬 check",
        highlight = "rendermarkdownsuccess",
        category = "obsidian",
      },
      done = {
        raw = "[!done]",
        rendered = "󰄬 done",
        highlight = "rendermarkdownsuccess",
        category = "obsidian",
      },
      question = {
        raw = "[!question]",
        rendered = "󰘥 question",
        highlight = "rendermarkdownwarn",
        category = "obsidian",
      },
      help = {
        raw = "[!help]",
        rendered = "󰘥 help",
        highlight = "rendermarkdownwarn",
        category = "obsidian",
      },
      faq = {
        raw = "[!faq]",
        rendered = "󰘥 faq",
        highlight = "rendermarkdownwarn",
        category = "obsidian",
      },
      attention = {
        raw = "[!attention]",
        rendered = "󰀪 attention",
        highlight = "rendermarkdownwarn",
        category = "obsidian",
      },
      failure = {
        raw = "[!failure]",
        rendered = "󰅖 failure",
        highlight = "rendermarkdownerror",
        category = "obsidian",
      },
      fail = {
        raw = "[!fail]",
        rendered = "󰅖 fail",
        highlight = "rendermarkdownerror",
        category = "obsidian",
      },
      missing = {
        raw = "[!missing]",
        rendered = "󰅖 missing",
        highlight = "rendermarkdownerror",
        category = "obsidian",
      },
      danger = {
        raw = "[!danger]",
        rendered = "󱐌 danger",
        highlight = "rendermarkdownerror",
        category = "obsidian",
      },
      error = {
        raw = "[!error]",
        rendered = "󱐌 error",
        highlight = "rendermarkdownerror",
        category = "obsidian",
      },
      bug = {
        raw = "[!bug]",
        rendered = "󰨰 bug",
        highlight = "rendermarkdownerror",
        category = "obsidian",
      },
      example = {
        raw = "[!example]",
        rendered = "󰉹 example",
        highlight = "rendermarkdownhint",
        category = "obsidian",
      },
      quote = {
        raw = "[!quote]",
        rendered = "󱆨 quote",
        highlight = "rendermarkdownquote",
        category = "obsidian",
      },
      cite = {
        raw = "[!cite]",
        rendered = "󱆨 cite",
        highlight = "rendermarkdownquote",
        category = "obsidian",
      },
    },
  },
}
